### ISSUE TITLE
Limited storage for credentials on Windows when using UTF8

### ISSUE THREAD

**Issue by Alexei-Barnes** [hwchen/keyring-rs#108]
I've got a use case for this library (Storing JWTs) which requires storing passwords of length ~1,500 bytes. This (encoded with UTF8) should fit fine in the [max storage size of a Windows credential](https://learn.microsoft.com/en-us/windows/win32/api/wincred/ns-wincred-credentiala#:~:text=member%20is%20ignored.-,CredentialBlobSize,This%20member%20cannot%20be%20larger%20than%20CRED_MAX_CREDENTIAL_BLOB_SIZE%20(5*512)%20bytes.,-CredentialBlob), of 5*512 (2,560) bytes.

However, because this library only offers using the `CredWriteW` method of storing credentials, it only stores them as UTF16. This effectively halves the available storage for ASCII encoded data such as a JWT to 1,280 bytes.

I suggest that we introduce a new pair of features, `windows-utf16` and `windows-utf8` (with `windows-utf16` as a default feature) that switch between UTF16 with CredWriteW, and UTF8 with CredWriteA. If this is a suggestion that you like, I'm happy to create a PR for that approach. Otherwise I'm open to hearing better approaches to solving my problem.

**Comment by Alexei-Barnes** [comment]
I've created a branch with the changes I'm proposing for preliminary review - let me know if this is on the right track or not.

**Comment by brotskydotcom** [comment]
By the way, @Alexei-Barnes, if your credential data is actually ASCII (or, better yet, alphanumeric), have you considered packing it into double-bytes and then transcoding that from UTF16 to UTF8?  That would leverage your recent fix of the length bug :).

**Comment by Alexei-Barnes** [comment]
That's a solid suggestion, I might try that in the short term

**Comment by brotskydotcom** [comment]
You might also want to look at [this code](https://github.com/adobe/adobe-license-decoder.rs/blob/98e13efbec724ab645faee7d306e8cc5a097bda9/src/types.rs#L233), which I wrote in a prior life.  It solves your long-credential problem by using multiple (consecutively-numbered) credentials each of which is small enough.

**Comment by Alexei-Barnes** [comment]
> System compatibility - The Windows Credential Manager and keyring interoperate nicely over (generic) CredentialW data. We would want to continue that, but I'm not sure how well the Credential Manager will deal with UTF8 data in those blobs.

Yea I was sort of hoping Windows would solve this problem under the hood somewhere if you use CredWriteA, but having just tried it out sadly it does not.

**Comment by brotskydotcom** [comment]
I'm going to close this as "won't fix".  I'm happy to reopen if you can find ways of addressing the compatibility issues. Thanks again, very much, for using the library and providing feedback!
