### ISSUE TITLE
Force user verification prior to accessing the keystore

### ISSUE THREAD

**Issue by Mikescops** [hwchen/keyring-rs#120]
Hello,

Thanks for your work on this package, it's great!

It might be a naive question, but is it possible to force a user verification when getting / setting a password?

For instance a use case would be that the user is asked for its fingerprint (or keystore main password) prior to accessing the password.

I understand it is not implemented here, just wondering if the most common keystore support this.

**Comment by brotskydotcom** [comment]
Hi @Mikescops, keystores other than the Linux keyring generally support the notion of a store being "locked" or "unlocked," but the details of how this works are very different between stores.  Also, for all the stores currently supported by this crate, whether a store is "locked" or "unlocked" is a system-wide property as opposed to being determined on a per-process basis.  So when this package goes to access a key, whether the user is prompted to unlock the store (and what that UI looks like) is beyond the scope of this package: it's handled by the store itself.

I hope this answers your question.  If I don't hear from you in a few days, I'll close this issue.

**Comment by Mikescops** [comment]
Thanks for the explanation, yes this answers my question!
