### ISSUE TITLE
Documentation error for Linux secret service backend

### ISSUE THREAD

**Issue by VorpalBlade** [hwchen/keyring-rs#121]
https://docs.rs/keyring/latest/keyring/secret_service/index.html claims the key "user" is used. This caused me much confusion and frustration for interoperability, because the actual key used is "username".

The documentation should be corrected.

**Comment by brotskydotcom** [comment]
Terribly sorry about that, @VorpalBlade!  Thanks so much for reporting it.  Fix is in progress and a new release will happen today (US Pacific Time).

**Comment by VorpalBlade** [comment]
Sorry if that came across too aggressive. Not my intention.
