### ISSUE TITLE
Add a way to only get the secret

### ISSUE THREAD

**Issue by jankatins** [hwchen/keyring-rs#130]
I want to use the example cli to interct with the keyrings on linux and mac and for that it would be nice to have a way to only return the password and not the `The password for 'jan@jasc-one' is 'whatever'`. Any chance to add such a cli interface?  E.g. `keyring-cli --service jasc-one  get --password-only`?

**Comment by brotskydotcom** [comment]
If you want to submit a pull request with this change, I'm happy to review it.

**Comment by brotskydotcom** [comment]
Thanks for the PR!  As I reviewed it, I realized that you also made another change (to return different exit statuses) that make the cli more suitable for scripted use.  So I decided to go further than you had and have opened PR #134.  Take a look and see if that does what you need.
