### ISSUE TITLE
Feature request: Disabling keyutils (and only using secret-service) on Linux

### ISSUE THREAD

**Issue by VorpalBlade** [hwchen/keyring-rs#153]
I'm trying to put my dependency tree on a diet and discovered that keyring seems to always pull in support for keyutils on Linux, even though I only ever use DBUS secret service (since I'm writing an interactive desktop program).

I don't see a way in your Cargo.toml to disable this. Would it be possible to make it a feature (enabled by default for backward compatibility of course)? Then those who don't need it can pull in keyring with no-default-features and just the feature `linux-secret-service`

**Comment by brotskydotcom** [comment]
My understanding is that keyutils is part of the kernel on Linux and so there are no additional dependencies included by the keyutils credential store. (Perhaps @landhb knows better?)

Are you asking for a way of compiling this crate so that the keyutils credential store is not even included in the build?

**Comment by VorpalBlade** [comment]
> My understanding is that keyutils is part of the kernel on Linux and so there are no additional dependencies included by the keyutils credential store.

keyring depends on the [linux-keyutils](https://lib.rs/crates/linux-keyutils) crate on Linux to interact with the kernel functionality. That in turn depends an old version of bitflags (the only crate in my dependency tree pulling in bitflags 1.x, causing duplication of that dependency). Which in turn pulls in more things. And so on.

**Comment by brotskydotcom** [comment]
> keyring depends on the [linux-keyutils](https://lib.rs/crates/linux-keyutils) crate on Linux to interact with the kernel functionality.

Oh, right, duh!  That will teach me not to look at my own Cargo.toml file before answering 🤦.

This is a good suggestion, and easy.  How about if I add a `linux-no-keyutils` (optional) feature to disable it, similar to `linux-no-secret-service`.  That way you can leave the default features in place when you load the crate.

**Comment by brotskydotcom** [comment]
Actually this issue makes me realize that the way the features have been defined are all wrong.  Even the platform dependencies should be controlled by features not by platform, in case users want to be using (for example) an internet-based store and don't want to pay the cost of the platform dependencies.

If no platform keystores are available, the mock keystore should be used as the default.

**Comment by brotskydotcom** [comment]
Release v2.2.0 fixes this issue.  You can now do `default-features = false, features = [linux-secret-service]` and the right thing will happen.
