### ISSUE TITLE
Is it possible to tell if secure storage is available before storing something?

### ISSUE THREAD

**Issue by John-Nagle** [hwchen/keyring-rs#168]
I'd like to know whether secure storage is available before trying to store anything. On some Linux systems, no secure storage seems to be available.

Use case: deciding whether to display a "Remember password" checkbox. 

Thanks.

**Comment by brotskydotcom** [comment]
Hi @John-Nagle, thanks for the question.

If I understand you correctly, you are asking whether there's a way to find out whether the lifetime of a stored credential survives a reboot.  This is similar to #147, and the sample code in that issue shows you how to use the `persistence` method on a credential store to answer that question.  Please let me know if this gives you what you need.

**Comment by John-Nagle** [comment]
Ah, good.
