### ISSUE TITLE
iOS issues: empty passwords, undefined externals

### ISSUE THREAD

**Issue by brotskydotcom** [hwchen/keyring-rs#190]
There are two issues with the iOS keystore in v3 (aside from #187 which @tmpfs has been kind enough to fix):

1. Retrieving an empty password/secret crashes. This is due to [this issue](https://github.com/kornelski/rust-security-framework/issues/206) in the security-framework code.  I have submitted [a PR](https://github.com/kornelski/rust-security-framework/pull/207) to fix this but don't know when it will be picked up.
2. Building and trying to link a static iOS library containing this crate leads to this error message due to [this issue](https://github.com/kornelski/rust-security-framework/issues/203) in the security-framework code (for which [a PR](https://github.com/kornelski/rust-security-framework/pull/204) has been merged but not released):
> unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`

In order to get a release out with the fix for #187, I am going to work around both these issues by using a stable fork of security-framework that fixes both of them.

**Comment by brotskydotcom** [comment]
Wonderfully, a new version (2.11.1) of [security-framework](https://crates.io/crates/security-framework) was just released a few hours ago.  So I can release version 3.0.2 with no iOS issues!!

**Comment by tmpfs** [comment]
Thanks @brotskydotcom , `3.0.2` is working for me on iOS and I get to remove `security-framework` from `patch.crates-io` 🚀
