### ISSUE TITLE
Suboptimal label when using the platform independent API with secret service backend

### ISSUE THREAD

**Issue by VorpalBlade** [hwchen/keyring-rs#208]
I played around with adding a password entry:

```rust
let password = rpassword::prompt_password("Password: ")?;
let entry = ini_merge::keyring::Entry::new(&service, &username)?;
entry.set_password(&password)?;
```

This works, but creates a very weirdly named item, since the label is apparently used as the title for the item (at least in KDE 6's KWallet, I don't use Gnome):
![image](https://github.com/user-attachments/assets/cf0fd172-2e77-49de-b0f3-e82d7742082b)
(Screenshot from 3.1.0, but I just checked 3.2.0 has the same issue.)

The cross platform API should ideally let you set the label to something more sensible.

I don't know how this looks in Gnome or on Windows or Mac, but it would be more useful to show the application name rather than the library name here. The version number is largely irrelevant (especially since it doesn't get updated if you set it again).

**Comment by brotskydotcom** [comment]
Since the label attribute is specific to secret service, I don't really see the inability to set it in a cross-platform way as a bug. But I can see other advantages for allowing users to specify, in a cross-platform way, additional attributes that specific platforms can make use of.
