### ISSUE TITLE
v1.0 checklist - for real this time

### ISSUE THREAD

**Issue by hwchen** [hwchen/keyring-rs#21]
I think enough people have used this library to go ahead and plan to release 1.0 soon.

The main points I need to address:

- [x] release v1.0 of secret-service dependency (part of the is removing some dependencies)

For the future:
- move cli binary to its own library, which would remove the binary's dependencies. I'm going to hold off on this, and maybe release 2.0, because I'm thinking of working on https://github.com/rust-lang/cargo/issues/1982. If anybody has feedback, please leave it here: https://github.com/hwchen/keyring-rs/issues/20

**Comment by hwchen** [comment]
using `secuirity-framework` for osx (instead of the cli) has been merged to master. So, that will merit a 0.x.0 release, and one step closer to 1.0

**Comment by hwchen** [comment]
68975839332e3dff0a5a3113a35ff5fb5e09a523 updates secret service dep to 1.0, removing gmp dep and updating rust-crypto to RustCrypto (fixing blank input encrypting/decrypting)

**Comment by hwchen** [comment]
cli was also moved to examples in 2bc3d8ef261aedddaf75d95ba7307458bc5cc4ab

**Comment by hwchen** [comment]
Now that 0.7.0 has been published, with big improvements in osx and linux backends, I'm just going to see if they're stable enough, and then I'll just add some CI and feel ready for 1.0

**Comment by hwchen** [comment]
@Rukenshia wanted to ping you on bringing keyring to 1.0, since your library is one of the biggest users judging from crates.io dependencies (and you've filed a lot of helpful issues). Please let me know if you upgrade to 0.7.0, and if you have any issues.

I'd probably feel comfortable enough to go to 1.0 if 0.7.0 was stable enough for you use.

**Comment by Rukenshia** [comment]
Thanks for the ping @hwchen , I will update to 0.7 as soon as I can and ask the users to update. Nobody reported issues recently (still on 0.6.1).

**Comment by adobeDan** [comment]
@hwchen I think this issue has been superseded by the work on #70 and our talk of a release there, yes?

**Comment by hwchen** [comment]
Yes, makes sense
