### ISSUE TITLE
Request for sponsorship?

### ISSUE THREAD

**Issue by mdtro** [hwchen/keyring-rs#219]
My employer, Sentry, contributes annually to open source projects (https://opensourcepledge.com/). We have an internal process where we nominate open source projects to receive funding.

I'd like to nominate `keyring`. Would the maintainers here be open to flipping on the Sponsorship bit in their GitHub profiles? :)

**Comment by brotskydotcom** [comment]
Wow, that’s very sweet of you, thanks!

I haven’t heard from Walther in forever, so I can’t speak for him. Do you
need both of us to agree, or just one of us?

I have no idea how Sponsorship works, so let me do some research and I’ll
get back to you. -d.
--
Dan – pronouns he/him

**Comment by mdtro** [comment]
We do not need both to agree. We'll sponsor who we can (either via GitHub Sponsors or [OpenCollective](https://opencollective.com/)). 

As maintainers, you all can split the sponsorship as you see fit of course. :) Ideally it'd be nice to give to both of you, but that's up to you.

**Comment by hwchen** [comment]
I'm happy to have the sponsorship for keyring go to @brotskydotcom, as I'm no longer involved in maintaining this crate. I do peek in every now and then and see all the heavy lifting that's being done, I'm just happy that keyring is in good hands :)

**Comment by brotskydotcom** [comment]
OK @mdtro, let's go ahead with this. I have changed my profile to allow sponsorships, and I will try adding a sponsor badge to this repository.  Thanks so much, again, for your generosity.

**Comment by brotskydotcom** [comment]
OK, I managed to give us a sponsorship badge. Thanks again.
