### ISSUE TITLE
"MacOsKeychainError" when unprivileged

### ISSUE THREAD

**Issue by Rukenshia** [hwchen/keyring-rs#22]
Hey,

I've had another user report problems with my tool, and this time it seems to be related to the user not unlocking their Keychain (or not having adminsitrative rights to do so). I'm not entirely sure how to reproduce this but it would be nice if I could get another error type for this, telling me that their Keychain just isn't accessible so that I can print a nice error message.

**Comment by hwchen** [comment]
Sounds good to me, will do.

**Comment by hwchen** [comment]
Sorry this has taken a while; I'll try to get this stuff done asap, but osx is not my usual dev platform and I need to re-setup my osx system.

**Comment by hwchen** [comment]
Sorry, it's been so long since this issue was filed. I've been busy with
other projects, and it's been a little difficult to get back into this
issue. I would be happy to take a pull request though. Otherwise, it will
likely be done sometime in the next few months (limited access to my mac
dev setup lately has also made this a bit difficult).

**Comment by Rukenshia** [comment]
Thank you, I don't think I will have time to work on this myself but you also don't need to rush this in any way. I've added documentation for troubleshooting as a solution for now in my project. Without this library I wouldn't even have keyring access so your work is very much appreciated!

**Comment by hwchen** [comment]
I haven't tested it, but I think that the new security-framework backend should solve this. You can see in the pr merge https://github.com/hwchen/keyring-rs/commit/9773a686184f9dfa05946a6418a4794035433fd8 that the mac keychain error now wraps the security framework error type. I've seen it give errors with codes, so I imagine that it will give one for when the keychain is not accessible.

I'll be publishing this in the next version in the next few days.

**Comment by hwchen** [comment]
0.7.0 published.

I'm going to close this issue for now, but feel free to open if you still can't get the error info you need.
