### ISSUE TITLE
macOS requests password twice for each `get_password`

### ISSUE THREAD

**Issue by Phrohdoh** [hwchen/keyring-rs#23]
Hi there and apologies for the possibly-confusing issue title!

This is my first programatic use of Keychain Access on macOS so what I'm running into may be normal/expected.

I am doing the following:

```rust
let access_key = keyring::Keyring::new("foo", "access_key").get_password().expect("Unable to get foo:access_key from system keychain");
```

And the system prompts me twice for an administrator password.

How can I get these creds from the keychain without prompting the user for a password?

What I'm building is an internal tool but ideally we'd not run it as root.

Any input would be greatly appreciated!

**Comment by hwchen** [comment]
Hmmm... I’m not sure why it prompts you twice for a password.

But, it is expected that you log in to access this keychain. Keyring uses the native vault for each os it runs on.

If my understanding is wrong (and I’m not an everyday OS X user), please let me know.

**Comment by Phrohdoh** [comment]
I may have to instruct users to "always allow" access to the keychain (which is functionality that Keychain Access provides to whitelist certain processes).  Nothing wrong with that, I was just hoping to do it all magically.

**Comment by hwchen** [comment]
Sorry I couldn’t provide something better, but let me know if there’s other improvements I can make.
