### ISSUE TITLE
MacOsKeychainError is not documented as far as I can tell

### ISSUE THREAD

**Issue by samuela** [hwchen/keyring-rs#24]
When the user denies keychain access on macOS, keyring returns a `MacOsKeychainError` error, which would be fine except that it's not really clear how this works since it's not documented anywhere here: https://docs.rs/keyring/0.6.1/keyring/struct.Keyring.html. I tried searching the docs for the string "MacOsKeychainError" but there weren't any results: https://docs.rs/keyring/0.6.1/keyring/struct.Keyring.html?search=MacOsKeychainError.

Also, how can one tell the difference between the user denying access vs other types of keychain errors in this case?

**Comment by hwchen** [comment]
Hi, sorry you couldn't find the error in the docs. Perhaps the docs are generated on linux, and so windows-specific and mac-specific errors are not rendered.

As for the non-specificity of the error, it's an issue I'd like to deal with soon. I have some more bandwidth coming up (as well as access to a mac again).

https://github.com/hwchen/keyring-rs/issues/22

**Comment by hwchen** [comment]
https://github.com/rust-lang/rust/issues/1998

Looks like cross-platform documentation is not-yet-solved.
I'll think about putting some of this missing documentation into the readme.

**Comment by hwchen** [comment]
the mac keychain error has been improved, see #22. Should be ready in the next version.

**Comment by hwchen** [comment]
added a note in the readme that a cargo command can be run to get docs locally. Next step would be to render docs on each platform and host them somewhere myself.

**Comment by adobeDan** [comment]
This is a good candidate for addressing in #70.  We should at least be able to say what the underlying errors are in each of the platforms in a cross-platform way.

**Comment by brotskydotcom** [comment]
closed with merge of #70.
