### ISSUE TITLE
Basic Travis CI testing? 

### ISSUE THREAD

**Issue by jasikpark** [hwchen/keyring-rs#27]
Would it be helpful to add Travis CI to run `RUST_TEST_THREADS=1 cargo test` on all PRs on all platforms? I feel like it would be.

**Comment by hwchen** [comment]
Yes, I've had it on my mind for a while but haven't quite gotten around to it. I'm happy to take PRs for it.

**Comment by hwchen** [comment]
well, I've been attempting linux on Travis. It's been difficult for me to mock the secret service test. So I'm leaving linux at just compiling for now. If anybody wants to attempt, I've mostly followed https://github.com/mitya57/secretstorage/blob/master/.travis.yml up until the point at which the mock secret-service is created using the run_test script. Unfortunately, even with the mock running, I'm still getting a `No such interface 'org.freedesktop.DBus.Properties' on object at path /`.

So something is off; maybe I'll come back to it later, but for now travisCI runs tests on osx and just compiles on linux. https://github.com/hwchen/keyring-rs/pull/29

**Comment by hwchen** [comment]
I've added travis and appveyor; linux is still not working well, but I'm going to leave that for the future.

**Comment by adobeDan** [comment]
This has been fixed with #66 and release 0.10.4.
