### ISSUE TITLE
Add testing of README.md examples?

### ISSUE THREAD

**Issue by jasikpark** [hwchen/keyring-rs#28]
https://blog.guillaume-gomez.fr/articles/2019-04-13+Keeping+Rust+projects%27+README.md+code+examples+up-to-date

The [doc-comment](https://crates.io/crates/doc-comment) crate has a macro `doctest!("../README.md");` that can test all examples in README.md to ensure they are up-to-date at all times.

**Comment by adobeDan** [comment]
This is fixed in #70 .
