### ISSUE TITLE
Iterate usernames?

### ISSUE THREAD

**Issue by liamdawson** [hwchen/keyring-rs#45]
Not sure if this is possible on all platforms, but I'm hoping there's a way to iterate usernames within the service. As an example, I'm creating a CLI where I'd like to support logging into to multiple accounts, but I'd currently need to record the usernames externally to support an autocomplete friendly list of accounts.

Something like this might work:

```rust
for username in keychain::Keychain::usernames("service_name") {
  println!("{:?}", username);
}
```

**Comment by hwchen** [comment]
@liamdawson if it's relatively straightforward on supported platforms, I think I'd be happy to support this. I don't have a lot of energy to put towards this, so it probably wouldn't happen unless somebody made a PR.

**Comment by adobeDan** [comment]
Hi @liamdawson, the underlying platform keychains do not all support the clear distinction between `username` and `service`, and none of them support wildcard searching.  So there's really no way to "iterate the keychain" looking for users of a given service.  So, I'm going to close this issue as "won't fix".
