### ISSUE TITLE
How does it work on raspbian ?

### ISSUE THREAD

**Issue by Riduidel** [hwchen/keyring-rs#46]
The tone of my question may appear rude, and if so, please forgive my poor english level.

So, I maintain a project where a GitHub angel has contributed this PR https://github.com/Riduidel/rrss2imap/pull/46 using your excellent crate to securely store passwords. This is SERIOUSLY cool.
Unfortunatly, there is one thing that prevent me from merging it now: I deploy that executbale on my raspberry running raspbian. And I don't understand how to have your wonderful crate running on Raspbian. Have you got any tutorial for Raspbian users ?

Thanks a lot

**Comment by hwchen** [comment]
Sorry, I don't have experience using raspbian. It looks like some of your issues are around libdbus. In the near future, when I have time (maybe next few weeks?) I'm thinking of updating one of the dependencies so that it no longer relies on libdbus, which I think might solve your problem.

**Comment by adobeDan** [comment]
@Riduidel It looks like lib-dbus is available on Raspbian now.  Can you please try using v0.10.4 on Raspbian?  I believe that the secret service update we took in 0.10.4 will make it work with the Raspbian dbus.

**Comment by brotskydotcom** [comment]
@Riduidel Our newest 1.0 release should work fine on Raspbian as both secret service and dbus run fine there.  Closing this question.
