### ISSUE TITLE
Fix macos feature test, tests

### ISSUE THREAD

**Issue by hwchen** [hwchen/keyring-rs#48]
I just published a version of keyring with a macos feature that allows specifying the keychain. The test is a bit mucked up, I'm planning on creating a new keychain file in a temp directory but it's not quite working.

In the meantime, I just switched to github actions. I don't think I lost the ability to test linux (readme notes that it was just building and not testing, since I couldn't get the dbus under x11 mock working).

**Comment by adobeDan** [comment]
This issue has two parts:

1. use of non-OS file-based keychains (not to be confused with use of alternate OS keychains, such as System, which is the subject of #44).  This capability has now been deprecated on Mac, and never existed on iOS, so I believe this feature should be removed.
2. fixing the tests on all platforms.  this has been addressed in the latest release.

@hwchen I am going to close this issue and leave #44 open.  Feel free to reopen if I have missed something.
