### ISSUE TITLE
Can't tell if a secret exists on Windows

### ISSUE THREAD

**Issue by edmellum** [hwchen/keyring-rs#49]
It looks to me like there's no way to get a `NoPasswordFound` from the Windows implementation which makes it hard to figure out if the library is failing or there's just no password set.

Long term maybe the API should be changed to return an `Option<T>` instead of returning an `Err` when there's no value?

**Comment by hwchen** [comment]
This is pretty important, I'll try to look into this pretty soon.

**Comment by hwchen** [comment]
Sorry it's taken a little while. I'm doing a round of maintenance on this project and `secret-service`, I should be getting to this after I [port](https://github.com/hwchen/secret-service-rs/pull/25) `secret-service` from dbus to zbus.
