### ISSUE TITLE
No backend error for Linux?

### ISSUE THREAD

**Issue by hwchen** [hwchen/keyring-rs#54]
See https://github.com/hwchen/secret-service-rs/issues/14

if secret service api not sound, perhaps return a new error, nobackendfound, instead of generic dbus error. Or perhaps some context would be sufficient?

**Comment by adobeDan** [comment]
This is being addressed by #70.  I still need to decide on all the error codes that we will surface.

**Comment by brotskydotcom** [comment]
closed with merge of #70.
