### ISSUE TITLE
Seeking maintainers

### ISSUE THREAD

**Issue by hwchen** [hwchen/keyring-rs#62]
Hi all,

I'm already unable to spend much, if any, energy on keyring-rs and secret-service-rs. In the near future, I'll have more family obligations and so will have even less energy.

So, I'm looking for some help. At the moment, I'm especially looking for people to help review/merge PRs. In the future, I may hand off publishing duties also, but I'm going to reserve that to myself for now.

I'd especially like maintainers from places that use keyring in production, as they'll have the most skin in the game. If you're interested in helping out, please mention your use-case in this issue.

**Comment by sayyedkamran** [comment]
Although I am not currently using it but I will be happy of I can be of any help, please. 

Syed Kamran

**Comment by phillipCouto** [comment]
I am more than happy to pitch in. We are actually using it to manage credentials for a desktop application my company ships. So the long term health of the project is important for my team.

**Comment by complexspaces** [comment]
Hi there,

I'd be happy to help with the maintenance of the `secret-service` crate. My current employer is using it in our Linux desktop app.

**Comment by hwchen** [comment]
Thanks to everybody for offering help! I'm going to prefer those who are currently depending on keyring and I'll send out invites shortly.

**Comment by phillipCouto** [comment]
> Thanks to everybody for offering help! I'm going to prefer those who are currently depending on keyring and I'll send out invites shortly.

Thank you @hwchen, will you be creating any maintainer guidelines to setup the expectations of how you want us to help run the project?

**Comment by adobeDan** [comment]
Hi @hwchen my company (Adobe) is also using keyring [in production](https://github.com/adobe/adobe-license-decoder.rs) and I would be happy to help with maintenance.  (FWIW, I currently have PR #61 pending which fixes issue #60.)

**Comment by hwchen** [comment]
Thanks to @phillipCouto and @adobeDan for helping to maintain.

For now, I think it will be helpful to do some triaging of the PRs. For new feature PRs I'd probably want to have some discussion to make sure nothing will break, I'd prefer to be rather conservative. For the near future I'd like to have final say on merging, but it'll be great to have additional eyes on all the code. I'd like to fast-track to a place where I'm not the bottleneck, without introducing breakage.

Sorry again for delay; new kid! but hopefully this will unlock forward progress/maintenance. Let me know if there's any other questions about how to move forward as maintainers.

**Comment by adobeDan** [comment]
Hi @hwchen apparently you sent my invitation on 6/11 when I was on vacation and not reading mail.  I'm back now and the invitation has expired.  Would you mind sending me a new invitation?  I'd love to help out here.

**Comment by adobeDan** [comment]
Hi @hwchen I finally have some time to look though the backlog of PRs.  Is there anywhere in particular you would like me to start?  Perhaps you could indicate PRs you want me to look at by assigning them to me?

**Comment by hwchen** [comment]
@adobeDan thanks! Let me look through the backlog tomorrow. I have a bit more energy at the moment also, hopefully we can get some stuff finished off.

**Comment by phillipCouto** [comment]
@hwchen  In regards to the backlog of PRs I am seeing them with conflicts and some recent changes may be stomping on older PRs.

How would you like to proceed? Do you want to have the older PRs merged through or do we ask the authors to reopen them based on latest if the changes are applicable.

Also how do you want to deal with breaking changes that would result in a major version bump versus a minor. I feel like this is important because changes to just the error enum is considered a breaking change.

**Comment by hwchen** [comment]
I think that with the new activity I'm prepared to have a major version bump. I haven't had time to review the older PRs, but we should probably check if there's any that can be merged before the breaking changes. Sorry I'm still a bit behind the ball on this, but feel free to ping on a PR that should have priority in merging.

**Comment by adobeDan** [comment]
Hi @phillipCouto, @hwchen, my 2 cents: 

I think once the changes for #67 and #70 are merged that we should do a major version bump, possibly even to 1.0.  #70 will be done by Monday, and #67 a few days after that.  If you two have any time, I think it would be great if you could review all the outstanding issues and PRs and mark them as one of:

* handled by #67 and #70 
* should be taken into #67 and #70 before they merge
* worth addressing eventually, but can wait until after 1.0 release
* should be closed

Does that make sense to you folks?

**Comment by phillipCouto** [comment]
> Hi @phillipCouto, @hwchen, my 2 cents:
> 
> I think once the changes for #67 and #70 are merged that we should do a major version bump, possibly even to 1.0. #70 will be done by Monday, and #67 a few days after that. If you two have any time, I think it would be great if you could review all the outstanding issues and PRs and mark them as one of:
> 
>     * handled by [Allow interoperability with 3rd-party conventions for keyring item names #67](https://github.com/hwchen/keyring-rs/pull/67) and [Error handling improvements #70](https://github.com/hwchen/keyring-rs/pull/70)
> 
>     * should be taken into [Allow interoperability with 3rd-party conventions for keyring item names #67](https://github.com/hwchen/keyring-rs/pull/67) and [Error handling improvements #70](https://github.com/hwchen/keyring-rs/pull/70) before they merge
> 
>     * worth addressing eventually, but can wait until after 1.0 release
> 
>     * should be closed
> 
> 
> Does that make sense to you folks?

@adobeDan that it does, maybe we can use labels to make it easier to classify issues and PRs so that it is evident that one of us has already reviewed it.

**Comment by adobeDan** [comment]
I think that's a great idea, @phillipCouto.  I've gone through all the existing issues and classified them.  I've also assigned to me all the ones that I think are going to be fixed by #70.  I think we will be in good shape at that point.

**Comment by brotskydotcom** [comment]
Hi @hwchen, with 3 active maintainers, I suspect you can close this issue.

**Comment by hwchen** [comment]
Makes sense, will close.
