### ISSUE TITLE
KeyringError::NoPasswordFound is not used on MacOS

### ISSUE THREAD

**Issue by Macil** [hwchen/keyring-rs#65]
On MacOS, if I try to get a nonexistent password, instead of getting an instance of KeyringError::NoPasswordFound I get `Mac Os Keychain Error: The specified item could not be found in the keychain.`.

The macos.rs file shows no uses of NoPasswordFound.

**Comment by adobeDan** [comment]
This is being addressed by #70.  Stay tuned!
