### ISSUE TITLE
GitHub search results for this repository

### ISSUE THREAD

**Issue by karashiiro** [hwchen/keyring-rs#71]
This package looks really useful, but it's surprisingly hard to find relative to how many stars it has. Here are some example searches that don't turn up this package:

[keyring rust](https://github.com/search?q=keyring+rust&type=repositories)
[keyring linux](https://github.com/search?l=Rust&q=keyring+linux&type=Repositories) and filtering Rust repositories
[keyring macos](https://github.com/search?q=keyring+macos+language%3ARust&type=Repositories&ref=advsearch&l=Rust&l=) and doing an advanced search for Rust
[keyring windows](https://github.com/search?q=keyring+windows&type=Repositories)
[windows credentials rust](https://github.com/search?q=windows+credentials+rust&type=Repositories), which does turn up my own package that I wrote under the impression that no others existed
[windows credential manager](https://github.com/search?q=windows+credential+manager+language%3ARust&type=Repositories&ref=advsearch&l=Rust&l=) and doing an advanced search for Rust
[crossplatform keyring](https://github.com/search?q=crossplatform+keyring&type=repositories)

I only found this package by searching *code* for [keyring macos rust](https://github.com/search?q=keyring+macos+rust&type=code).

In fairness, just searching keyring and doing an [advanced search for Rust](https://github.com/search?q=keyring+language%3ARust&type=Repositories&ref=advsearch&l=Rust&l=) specifically does turn up this package at the top, but it's odd that none of the other searches show this anywhere in the results.

I think this problem would be solved by just adding some tags to the repository using some of the keywords I tried.

**Comment by brotskydotcom** [comment]
Hi @karashiiro thanks much for pointing this out.  I've never really looked at keyboarding a repository before, so this will be a good learning experience.  I think we are more interested in this being discoverable on crates.io than we are on GitHub, but it can't hurt to make it discoverable both places.

**Comment by brotskydotcom** [comment]
Hey @hwchen it looks like only the repository administrators can add topic keywords, so I've assigned this to you.  If you want to make me an admin, feel free to assign it back to me and I can take care of it.

**Comment by hwchen** [comment]
I've added topic keywords @karashiiro, thanks for bringing this up.
